global:
  message: Welcome to global microservices Environemnt
logging:
  level:
    root: INFO
  erureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details:always
