global:
  message: Welcome to global microservices Environemnt
server:
  port:8082
message: Hello from Dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
