global:
  message: Welcome to order services prod Environemnt
server:
  port:8085
message: Hello from Prod
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
